# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '11.0'
inhibit_all_warnings!

target 'TTSwiftHub' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TTSwiftHub
  
  # Networking
  pod 'Moya/RxSwift'  # https://github.com/Moya/Moya
  pod 'Apollo', "0.25.0"  # https://github.com/apollographql/apollo-ios
  
  # JSON Mapping
  pod 'Moya-ObjectMapper/RxSwift'  # https://github.com/ivanbruel/Moya-ObjectMapper
  
  # Date
  pod 'SwiftDate', '~> 6.0'  # https://github.com/malcommac/SwiftDate
  
  # Keychain
  pod 'KeychainAccess', '~> 4.0'  # https://github.com/kishikawakatsumi/KeychainAccess
  
  # Rx Extensions
  pod 'RxDataSources', '~> 4.0'  # https://github.com/RxSwiftCommunity/RxDataSources
  pod 'RxSwiftExt', '~> 5.0'  # https://github.com/RxSwiftCommunity/RxSwiftExt
  pod 'NSObject+Rx', '~> 5.0'  # https://github.com/RxSwiftCommunity/NSObject-Rx
  pod 'RxViewController', '~> 1.0'  # https://github.com/devxoul/RxViewController
  pod 'RxGesture', '~> 3.0'  # https://github.com/RxSwiftCommunity/RxGesture
  pod 'RxOptional', '~> 4.0'  # https://github.com/RxSwiftCommunity/RxOptional
  pod 'RxTheme', '~> 4.0'  # https://github.com/RxSwiftCommunity/RxTheme

  # UI
  pod 'KafkaRefresh'  # https://github.com/OpenFeyn/KafkaRefresh
  pod 'DZNEmptyDataSet'  # https://github.com/dzenbot/DZNEmptyDataSet
  pod 'Localize-Swift'  # https://github.com/marmelroy/Localize-Swift
  pod 'Hero', :git => 'https://github.com/HeroTransitions/Hero.git', :branch => 'develop'  # https://github.com/lkzhao/Hero
  pod 'RAMAnimatedTabBarController'  # https://github.com/Ramotion/animated-tab-bar
  pod 'Toast-Swift', '~> 5.0'  # https://github.com/scalessec/Toast-Swift
  
  # Auto Layout
  pod 'SnapKit'  # https://github.com/SnapKit/SnapKit
  
  # Tools
  pod 'R.swift'  # https://github.com/mac-cain13/R.swift
#  pod 'SwiftLint', '0.39.2'  # https://github.com/realm/SwiftLint

  # Code Quality
  pod 'FLEX', '~> 4.0', :configurations => ['Debug']  # https://github.com/Flipboard/FLEX
  pod 'SwifterSwift', '~> 5.0'  # https://github.com/SwifterSwift/SwifterSwift
  pod 'BonMot', '~> 5.0'  # https://github.com/Rightpoint/BonMot
  
  # Logging
  pod 'CocoaLumberjack/Swift'  # https://github.com/CocoaLumberjack/CocoaLumberjack
  
  # Ads
  pod 'Google-Mobile-Ads-SDK'

  target 'TTSwiftHubTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TTSwiftHubUITests' do
    # Pods for testing
  end

end

post_install do |installer|
    # Cocoapods optimization, always clean project after pod updating
    Dir.glob(installer.sandbox.target_support_files_root + "Pods-*/*.sh").each do |script|
        flag_name = File.basename(script, ".sh") + "-Installation-Flag"
        folder = "${TARGET_BUILD_DIR}/${UNLOCALIZED_RESOURCES_FOLDER_PATH}"
        file = File.join(folder, flag_name)
        content = File.read(script)
        content.gsub!(/set -e/, "set -e\nKG_FILE=\"#{file}\"\nif [ -f \"$KG_FILE\" ]; then exit 0; fi\nmkdir -p \"#{folder}\"\ntouch \"$KG_FILE\"")
        File.write(script, content)
    end
    
    # Enable tracing resources
    installer.pods_project.targets.each do |target|
      if target.name == 'RxSwift'
        target.build_configurations.each do |config|
          if config.name == 'Debug'
            config.build_settings['OTHER_SWIFT_FLAGS'] ||= ['-D', 'TRACE_RESOURCES']
          end
        end
      end
    end
end
